JUBATUS_HOME=$HOME/local
export JUBATUS_HOME

PATH=$JUBATUS_HOME/bin:$PATH
export PATH

CPLUS_INCLUDE_PATH=$JUBATUS_HOME/include
export CPLUS_INCLUDE_PATH

LDFLAGS=-L$JUBATUS_HOME/lib
export LDFLAGS

LD_LIBRARY_PATH=$JUBATUS_HOME/lib
export LD_LIBRARY_PATH

PKG_CONFIG_PATH=$JUBATUS_HOME/lib/pkgconfig
export PKG_CONFIG_PATH
