JUBATUS_HOME=$HOME/local

PATH=$JUBATUS_HOME/bin:$PATH

CPLUS_INCLUDE_PATH=$JUBATUS_HOME/include
export CPLUS_INCLUDE_PATH

export PATH

export set LDFLAGS=-L$JUBATUS_HOME/lib

LD_LIBRARY_PATH=$JUBATUS_HOME/lib
export LD_LIBRARY_PATH

PKG_CONFIG_PATH=$JUBATUS_HOME/lib/pkgconfig
export PKG_CONFIG_PATH
